version: "3.8"

services:
  transportService:
    image: transport-backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - /app/transportService:/data
    environment:
      REDIS_HOST: redis
    networks:
      - transport_net
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - /app/redis/redis.conf:/etc/redis/redis.conf
      - /app/redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - transport_net
    command: redis-server /etc/redis/redis.conf

  mysql:
    image: mysql
    container_name: MySQL8
    environment:
      MYSQL_ROOT_PASSWORD: 952490637
      MYSQL_DATABASE: 'transport'
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs

  transportFrontend:
    image: transport-frontend
    container_name: frontend
    ports:
      - "5000:4000"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - transport_net

networks:
  transport_net: